export interface PrepayVsInvestInput {
  outstandingLoan: number
  remainingTenureYears: number
  loanInterestRate: number
  extraMonthlyAmount: number
  expectedReturnRate: number
}

export interface PrepayVsInvestResult {
  // Base loan
  regularEMI: number
  baseTotalInterest: number

  // Prepay scenario
  prepayTotalInterest: number
  interestSaved: number
  newTenureMonths: number
  tenureSavedMonths: number

  // Invest scenario
  investTotalReturns: number
  investTotalCorpus: number

  // Comparison
  betterOption: "prepay" | "invest"
  netBenefit: number // Difference between the two options
}

/**
 * Calculates regular EMI
 */
function calculateEMI(
  principal: number,
  annualRate: number,
  tenureMonths: number
): number {
  const r = annualRate / 12 / 100
  if (r === 0) return principal / tenureMonths
  return (
    (principal * r * Math.pow(1 + r, tenureMonths)) /
    (Math.pow(1 + r, tenureMonths) - 1)
  )
}

/**
 * Simulates a loan with an extra monthly payment to find the new tenure and interest
 */
function simulatePrepayment(
  principal: number,
  annualRate: number,
  regularEMI: number,
  extraMonthly: number,
  maxMonths: number
) {
  let balance = principal
  const monthlyRate = annualRate / 12 / 100
  let monthsTaken = 0
  let totalInterest = 0

  while (balance > 0 && monthsTaken < maxMonths * 2) {
    // safety bound
    monthsTaken++
    const interest = balance * monthlyRate
    totalInterest += interest

    const payment = regularEMI + extraMonthly
    const principalPaid = payment - interest

    if (principalPaid >= balance) {
      // Final month
      balance = 0
    } else {
      balance -= principalPaid
    }
  }

  return { monthsTaken, totalInterest }
}

/**
 * Calculates future value of a regular monthly investment (SIP)
 */
function calculateSIP(
  monthlyInvestment: number,
  annualRate: number,
  tenureMonths: number
): number {
  const r = annualRate / 12 / 100
  if (r === 0) return monthlyInvestment * tenureMonths
  return monthlyInvestment * ((Math.pow(1 + r, tenureMonths) - 1) / r) * (1 + r)
}

/**
 * Compares prepaying a loan vs investing the extra amount
 */
export function calculatePrepayVsInvest(
  input: PrepayVsInvestInput
): PrepayVsInvestResult {
  const {
    outstandingLoan,
    remainingTenureYears,
    loanInterestRate,
    extraMonthlyAmount,
    expectedReturnRate,
  } = input
  const tenureMonths = remainingTenureYears * 12

  // 1. Base Loan Calculation
  const regularEMI = calculateEMI(
    outstandingLoan,
    loanInterestRate,
    tenureMonths
  )
  const baseTotalInterest = regularEMI * tenureMonths - outstandingLoan

  // 2. Prepay Scenario
  const { monthsTaken: newTenureMonths, totalInterest: prepayTotalInterest } =
    simulatePrepayment(
      outstandingLoan,
      loanInterestRate,
      regularEMI,
      extraMonthlyAmount,
      tenureMonths
    )
  const interestSaved = Math.max(0, baseTotalInterest - prepayTotalInterest)
  const tenureSavedMonths = Math.max(0, tenureMonths - newTenureMonths)

  // 3. Invest Scenario
  const investTotalCorpus = calculateSIP(
    extraMonthlyAmount,
    expectedReturnRate,
    tenureMonths
  )
  const investTotalInvested = extraMonthlyAmount * tenureMonths
  const investTotalReturns = Math.max(
    0,
    investTotalCorpus - investTotalInvested
  )

  // 4. Comparison
  // We compare the interest saved by prepaying vs the returns generated by investing.
  const betterOption = investTotalReturns > interestSaved ? "invest" : "prepay"
  const netBenefit = Math.abs(investTotalReturns - interestSaved)

  return {
    regularEMI: Math.round(regularEMI),
    baseTotalInterest: Math.round(baseTotalInterest),
    prepayTotalInterest: Math.round(prepayTotalInterest),
    interestSaved: Math.round(interestSaved),
    newTenureMonths,
    tenureSavedMonths,
    investTotalReturns: Math.round(investTotalReturns),
    investTotalCorpus: Math.round(investTotalCorpus),
    betterOption,
    netBenefit: Math.round(netBenefit),
  }
}
